schema: ./schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:6532/api/graphql
#      headers:
#        Authorization: ${GRAPHQL_TOKEN}
      introspect: true
