schema: ./schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://waifu.neoforged.net/api/graphql
      headers:
        Authorization: ${GRAPHQL_TOKEN}
      introspect: true
