plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version "9.0.0-beta6"
    id 'net.neoforged.gradleutils' version '3.0.0'
}

group = 'net.neoforged.waifu'

gradleutils.version {
    tags.includeFilters.add('2.0')
}

println("Version: ${project.version = gradleutils.version}")

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
    maven {
        url 'https://maven.neoforged.net/'
        mavenContent {
            includeGroupAndSubgroups('net.neoforged')
            includeGroupAndSubgroups('cpw')
        }
    }
    maven {
        url = 'https://m2.chew.pro/releases'
    }
    maven { url 'https://www.jitpack.io' }
}

application {
    mainClass = 'net.neoforged.waifu.Main'
}

dependencies {
    implementation 'io.javalin:javalin:7.1.0'
    implementation 'org.slf4j:slf4j-simple:2.0.16'

    implementation 'org.ow2.asm:asm:9.8'
    implementation 'com.electronwill.night-config:toml:3.6.6'
    implementation 'com.electronwill.night-config:json:3.6.6'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.google.guava:guava:33.4.0-jre'
    implementation 'org.apache.maven:maven-artifact:3.9.9'

    implementation 'net.dv8tion:JDA:6.0.0'

    // TODO - switch back to the normal maven one once https://github.com/Chew/JDA-Chewtils/pull/93 is merged
    // implementation 'pw.chew:jda-chewtils:2.0'
    implementation 'com.github.Chew:JDA-Chewtils:39a83bd8357b6dd0ea94f7b20bd4f611d84beaa9'

    implementation 'net.neoforged:AutoRenamingTool:2.0.3'

    implementation 'io.github.matyrobbrt:curseforgeapi:2.3.5'

    implementation 'org.flywaydb:flyway-core:11.20.3'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql:11.20.3'

    implementation 'org.jdbi:jdbi3-core:3.32.0'
    implementation 'org.jdbi:jdbi3-sqlobject:3.32.0'
    implementation 'org.jdbi:jdbi3-postgres:3.32.0'
    implementation 'org.xerial:sqlite-jdbc:3.41.2.2'
    implementation 'org.postgresql:postgresql:42.7.2'

    implementation 'com.graphql-java:graphql-java:24.1'
    implementation 'com.graphql-java:graphql-java-extended-scalars:24.0'

    compileOnly 'org.jetbrains:annotations:26.0.2'
}

abstract class Log extends DefaultTask {
    @OutputFile
    abstract RegularFileProperty getOutput()

    Log() {
        outputs.upToDateWhen { false }
    }

    @TaskAction
    void exec() {
        new ProcessBuilder('git', 'log', '-5', '--pretty=oneline')
                .redirectOutput(getOutput().asFile.get())
                .start().waitFor()
    }
}

tasks.register('gitLog', Log) {
    it.output.set(project.layout.buildDirectory.file('gitlog'))
}

jar {
    manifest.attributes([
            'Implementation-Version': project.version
    ])
}

shadowJar {
    mergeServiceFiles()
    archiveClassifier = 'all'
    archiveFile.set(project.layout.buildDirectory.file("libs/waifu-all.jar"))
    from('web-interface/.output/public') {
        into 'web/static'
    }
    from(tasks.gitLog.output)
}
