# noinspection GraphQLUnresolvedReference,GraphQLMissingType

directive @predicateType on INPUT_OBJECT
directive @implement(interfaces: [String!]!) on OBJECT
directive @specifiedBy(url: String!) on SCALAR
directive @paginated on FIELD_DEFINITION

scalar DateTime @specifiedBy(url: "https://scalars.graphql.org/andimarek/date-time.html")

schema {
    query: Query
}

enum Loader {
    "The NeoForge loader (https://github.com/NeoForged)"
    NeoForge,
    "The NeoForge loader (https://github.com/FabricMC)"
    Fabric,
    "The Forge loader (https://github.com/MinecraftForge)"
    Forge
}

type Query {
    "Get all indexed game versions"
    gameVersions: [GameVersion!]!

    "Query a game version based on the Minecraft version and the loader"
    gameVersion(
        "The Minecraft version"
        version: String!,
        "The loader"
        loader: Loader!
    ): GameVersion
}

type GameVersion {
    "The Minecraft version this game version indexes"
    version: String!
    "The loader this game version indexes"
    loader: Loader!

    "Query mods from the database"
    mods(
        "Optional filter applied to the query"
        where: ModPredicate
    ): Mod @paginated

    """
    Get the mods from the database that have the given IDs.
    Note that the mods are not returned in a specific order relative to the input IDs.
    """
    modsById(
        """
        The mod IDs to query.
        If it exceeds the maximum amount of elements that a single query can return you can paginate it further.
        """
        ids: [Int!]!
    ): Mod @paginated
}

"Represents an object that is identifiable by an unique ID (within its category)"
interface Identifiable {
    "The unique ID of this object"
    id: Int!
}

type Mod @implement(interfaces: ["Identifiable"]) {
    "The name of this mod (derived from mod metadata, jar contents or maven coordinates)"
    name: String!
    "The last indexed version of this mod"
    version: String!

    "The authors of this mod (derived from mod metadata)"
    authors: String
    "The license of this mod (derived from mod metadata)"
    license: String

    "The ID of the CurseForge project associated with this mod"
    curseforgeProjectId: Int
    "The ID of the Modrinth project associated with this mod"
    modrinthProjectId: String
    "The maven coordinates of this mod (only set if this mod was JiJ'd by another mod)"
    mavenCoordinates: String

    "The sections of the manifest of the last jar indexed for this mod"
    manifest: [ManifestEntry!]!

    "Get the classes this mod defines. Optionally takes in a filter on the class name"
    classes(where: ClassPredicate, order: ClassOrdering, limit: Int): [String!]!

    "Get the tags this mod defines for the given registry"
    tags(
        """
        The registry to get tags for.
        The format is namespace:registry (e.g. "minecraft:item" or "minecraft:worldgen/biome")
        """
        registry: String!,
        "An optional filter applied to the returned tags"
        where: TagFilePredicate,
        "Limit the amount of tags returned"
        limit: Int
    ): [TagFile!]!

    "The time this mod was last indexed"
    indexedOn: DateTime
}

"Represents a manifest entry (section)"
type ManifestEntry {
    "The name of this manifest section (the main section has this field blank)"
    name: String!
    "The attributes in this section"
    attributes: [ManifestAttribute!]!
}

"Represents a manifest attribute (e.g. 'Implementation-Version: 1.0')"
type ManifestAttribute {
    "The key of this attribute"
    key: String!
    "The value of this attribute"
    value: String!
}

"A Minecraft tag file"
type TagFile {
    "The name of this tag (e.g. minecraft:mineable/pickaxe)"
    name: String!
    "The entries added to this tag. These can be either normal objects (e.g. minecraft:stone) or other tags, denoted by a # at the start (e.g. #minecraft:head_armor)"
    entries("An optional filter applied to the entries returned" where: StringPredicate): [String]!
    """
    Whether this tag overrides all previously added entries.
    Corresponds to the "replace" field in the tag JSON.
    """
    replace: Boolean!
}

"Used to filter tags based on different criteria"
input TagFilePredicate @predicateType @oneOf {
    "Filter based on the tag name"
    name: StringPredicate

    """
    If set to true, only tags that override existing values will be returned.
    If set to false, only tags that do not override existing values will be returned.
    """
    replace: Boolean

    "A tag file will match this predicate if any of its direct entries matches the given predicate"
    anyEntry: StringPredicate
}

"Used to filter mods based on different criteria"
input ModPredicate @predicateType @oneOf {
    "Filter based on the mod's name (derived from mod metadata, jar contents or maven coordinates)"
    name: StringPredicate
    "Filter based on the mod's authors (derived from mod metadata)"
    authors: StringPredicate
    "Filter based on the mod's license (derived from mod metadata)"
    license: StringPredicate
    "Filter based on the mod's description (derived from mod metadata)"
    description: StringPredicate
    """
    Filter based on the mod's mod IDs (derived from mod metadata).
    On Neo/Forge only one of the IDs of a multi mod jar needs to match the filter.
    """
    modId: StringPredicate

    "A mod will match if any of the classes it defines has a name that matches the given filter"
    anyClassName: StringPredicate
    "A mod will match if any of the manifest attributes its jar has matches the given filter"
    anyManifestAttribute: ManifestAttributePredicate

    "A mod will match if it is contained in the pack with the given ID"
    inPack: ProjectId

    "A mod will match if it is associated with the CurseForge project with the given ID"
    curseforgeProjectId: Int
    "A mod will match if it is associated with the Modrinth project with the given ID"
    modrinthProjectId: String

    "A mod will match if the date it has last been indexed on matches the given predicate"
    indexed: DatePredicate
}

"Represents the ID of a project on CurseForge or Modrinth"
input ProjectId @oneOf {
    "The ID of the project on CurseForge"
    curseforge: Int
    "The ID of the project on Modrinth"
    modrinth: String
}

"Used to filter classes based on different criteria"
input ClassPredicate @predicateType @oneOf {
    "Filter based on the class' JVM name"
    name: StringPredicate
}

"Used to filter manifest attributes based on their name and/or value"
input ManifestAttributePredicate @predicateType @oneOf {
    "Filter based on the attribute name (key)"
    name: StringPredicate
    "Filter based on the attribute value"
    value: StringPredicate
}

"Information about pagination in a connection."
type PageInfo {
    "Whether there are more elements past the last element of the response"
    hasNextPage: Boolean!

    """
    Whether there are more elements before the last element of the response.
    Note that this field may be false even if earlier pages exist when it is too expensive to check if earlier pages exist.
    """
    hasPreviousPage: Boolean!

    "The cursor ID that points to the first element returned, if there is one"
    startCursor: ID

    "The cursor ID that points to the last element returned, if there is one"
    endCursor: ID
}

"""
Represents a way of filtering string inputs based on different rules that are either logical operators
on other filters (NOT, AND, OR) or exact / regex matches.
"""
input StringPredicate @oneOf @predicateType {
    "The string being filtered must be equal to the given string."
    equals: String

    "The string being filtered must match the given regex pattern."
    matches: String

    "The string being filtered must start with the given string."
    startsWith: String
}

"A predicate applied to date types"
input DatePredicate @oneOf {
    "Matches if the date is before (smaller than) the given date"
    before: DateTime
    "Matches if the date is after (greater than) the given date"
    after: DateTime
}

input PaginationInput {
    "The cursor ID of the element to search after"
    after: Int

    "Maximum amount of elements to query"
    limit: Int
}

enum OrderRule {
    value,
    length
}

enum OrderDirection {
    asc,
    desc
}

input OrderMethod {
    by: OrderRule = value
    direction: OrderDirection = asc
}

input ClassOrdering @oneOf {
    name: OrderMethod
}
