# noinspection GraphQLUnresolvedReference,GraphQLMissingType

directive @predicateType on INPUT_OBJECT
directive @implement(interfaces: [String!]!) on OBJECT | INTERFACE
directive @specifiedBy(url: String!) on SCALAR
directive @paginated on FIELD_DEFINITION
directive @orderBy on FIELD_DEFINITION

scalar DateTime @specifiedBy(url: "https://scalars.graphql.org/andimarek/date-time.html")

scalar JSON

schema {
    query: Query
}

enum Loader {
    "The NeoForge loader (https://github.com/NeoForged)"
    NeoForge,
    "The NeoForge loader (https://github.com/FabricMC)"
    Fabric,
    "The Forge loader (https://github.com/MinecraftForge)"
    Forge
}

type Query {
    "Get all indexed game versions"
    gameVersions(
        "Optional filter. Return only game versions with this loader"
        loader: Loader
    ): [GameVersion!]!

    "Query a game version based on the Minecraft version and the loader"
    gameVersion(
        "The Minecraft version"
        version: String!,
        "The loader"
        loader: Loader!
    ): GameVersion
}

type GameVersion {
    "The Minecraft version this game version indexes"
    version: String!
    "The loader this game version indexes"
    loader: Loader!

    "Query mods from the database"
    mods(
        "Optional filter applied to the query"
        where: ModPredicate
    ): Mod @paginated

    """
    Get the mods from the database that have the given IDs.
    Note that the mods are not returned in a specific order relative to the input IDs.
    """
    modsById(
        """
        The mod IDs to query.
        If it exceeds the maximum amount of elements that a single query can return you can paginate it further.
        """
        ids: [Int!]!
    ): Mod @paginated

    "Get the classes known by this game version that optionally match the given predicate"
    classes(
        "Optional filter applied to the query"
        where: ClassPredicate
    ): Class @paginated
}

"Represents an object that is identifiable by an unique ID (within its category)"
interface Identifiable {
    "The unique ID of this object"
    id: Int!
}

"A base interface used to describe the simple properties of an indexed Mod"
interface BaseMod @implement(interfaces: "Identifiable") {
    "The name of this mod (derived from mod metadata, jar contents or maven coordinates)"
    name: String!
    "The last indexed version of this mod"
    version: String!

    "The authors of this mod (derived from mod metadata)"
    authors: String
    "The license of this mod (derived from mod metadata)"
    license: String

    "The ID of the CurseForge project associated with this mod"
    curseforgeProjectId: Int
    "The ID of the Modrinth project associated with this mod"
    modrinthProjectId: String
    "The maven coordinates of this mod (only set if this mod was JiJ'd by another mod)"
    mavenCoordinates: String

    "The sections of the manifest of the last jar indexed for this mod"
    manifest: [ManifestEntry!]!

    "The time this mod was last indexed"
    indexedOn: DateTime
}

"""
A mod instance which has only basic properties available (properties that do not require joining on tables other than `mods`).
These are returned by objects associated with a mod like class definitions.
To "upgrade" a lightweight mod to a _Mod_ you can use `modsById`.
"""
type LightweightMod @implement(interfaces: ["Identifiable", "BaseMod"]) {
    _: String
}

"Represents a full mod from which data that requires more complex processing can be queries (classes, tags etc.)"
type Mod @implement(interfaces: ["Identifiable", "BaseMod"]) {
    "Get the classes this mod defines. Optionally takes in a filter on the class name"
    classes(where: ClassDefinitionPredicate, limit: Int): [ClassDefinition!]!

    "Get the tags this mod defines for the given registry"
    tags(
        """
        The registry to get tags for.
        The format is namespace:registry (e.g. `minecraft:item` or `minecraft:worldgen/biome`)
        """
        registry: String!,
        "An optional filter applied to the returned tags"
        where: TagFilePredicate,
        "Limit the amount of tags returned"
        limit: Int
    ): [TagFile!]!

    "Get the data maps this mod defines for the given registry"
    dataMaps(
        """
        The registry to get data maps for.
        The format is namespace:registry (e.g. `minecraft:item` or `minecraft:worldgen/biome`)
        """
        registry: String!,
        "An optional filter applied to the returned data map files"
        where: DataMapFilePredicate,
        "Limit the amount of data map files returned"
        limit: Int
    ): [DataMapFile!]!

    "Get the enum extensions this mod defines"
    enumExtensions(
        "An optional filter applied to the returned entries"
        where: EnumExtensionPredicate,
        "Limit the amount of entries returned"
        limit: Int
    ): [EnumExtension!]!
}

"Represents a manifest entry (section)"
type ManifestEntry {
    "The name of this manifest section (the main section has this field blank)"
    name: String!
    "The attributes in this section"
    attributes: [ManifestAttribute!]!
}

"Represents a manifest attribute (e.g. 'Implementation-Version: 1.0')"
type ManifestAttribute {
    "The key of this attribute"
    key: String!
    "The value of this attribute"
    value: String!
}

"A Minecraft tag file"
type TagFile {
    "The name of this tag (e.g. minecraft:mineable/pickaxe)"
    name: String!
    "The entries added to this tag. These can be either normal objects (e.g. minecraft:stone) or other tags, denoted by a # at the start (e.g. #minecraft:head_armor)"
    entries("An optional filter applied to the entries returned" where: StringPredicate): [String!]!
    """
    Whether this tag overrides all previously added entries.
    Corresponds to the "replace" field in the tag JSON.
    """
    replace: Boolean!
}

"A NeoForge data map file"
type DataMapFile {
    "The name of this data map (e.g. `neoforge:compostables`)"
    name: String!
    "The entries in this file"
    entries: [DataMapEntry!]!
}

"An entry in a NeoForge data map file"
type DataMapEntry {
    "The key of this entry. Can either be the location of a registry object (e.g. `minecraft:coal_block`) or a tag, denoted by a # at the start (e.g. `#minecraft:logs`)"
    key: String!
    "The value of this entry - i.e. the object attached to the entry with the `key` ID or to entries within the tag, if the `key` is a tag"
    value: JSON!
    """
    Whether this entry replaces previously added entries for objects within the key without invoking mergers.
    Corresponds to the "replace" field at either the top of the data map file or within individual entries.
    """
    replace: Boolean!
}

"A NeoForge enum extension entry"
type EnumExtension {
    "The internal name of the enum this extension targets"
    enum: String!
    "The descriptor of the constructor this extension uses"
    constructor: String!
    "The name of the enum field this extension adds"
    name: String!
    "The source of the parameters"
    parameters: JSON!
}

"An annotation instance (the type and its value as a JSON object)"
type Annotation {
    "The type of the annotation - e.g. `java/lang/Deprecated`"
    type: String!

    "The value of this annotation as a JSON object"
    value: JSON
}

"Represents an object that can be annotated - method, field or class definition"
interface Annotatable {
    "Returns annotations on this object matching the given predicate"
    annotations("An optional filter to apply to the query" where: AnnotationPredicate): [Annotation!]!
}

"Used to filter annotations based on different criteria"
input AnnotationPredicate @predicateType @oneOf {
    "Filter based on the annotation type"
    type: StringPredicate
}

"A base interfaces for classes identified by their name (e.g. `java/lang/String`)"
interface BaseClass @implement(interfaces: "Identifiable") {
    "The name of this class"
    name: String!

    """
    The methods of this class, optionally matching the given predicate.
    Note that it is not guaranteed that the methods returned have a concrete implementation.
    """
    methods(
        "Optional filter to apply to the query"
        where: MethodPredicate,
        "Limit the amount of methods returned"
        limit: Int
    ): [Method!]!

    """
    The fields of this class, optionally matching the given predicate.
    Note that it is not guaranteed that the fields returned have a concrete implementation.
    """
    fields(
        "Optional filter to apply to the query"
        where: FieldPredicate,
        "Limit the amount of fields returned"
        limit: Int
    ): [Field!]!

    "Returns all known concrete definitions of the class"
    definitions: [ClassDefinition!]!
}

"""
A class identified by its name (e.g. `java/lang/String`) as returned by `Class.inheritors` which has a certain depth from the root of the inheritance tree.
"""
type InheritanceTreeClass @implement(interfaces: ["Identifiable", "BaseClass"]) {
    """
    The depth of this class in the inheritance tree.
    Classes with a depth of 1 are direct children of the class from which the search was started, classes with a depth of 2 are their children and so on.
    """
    depth: Int! @orderBy
}

"Used to filter inheriting classes based on different criteria"
input InheritorPredicate @predicateType @oneOf {
    "Filter based on the class' JVM name"
    name: StringPredicate

    "Filter based on the class' depth in the inheritance tree"
    depth: IntPredicate
}

"""
A class identified by its name (e.g. `java/lang/String`) from which an inheritor search can be started.
"""
type Class @implement(interfaces: ["Identifiable", "BaseClass"]) {
    """
    Returns all known classes that inherit from this class and which optionally match the given filter.
    """
    inheritors(
        """
        A filter to apply to the returned classes.
        Note that this filter applies on each node individually. This means that when a class is removed by the predicate, classes that further inherit from it will still be returned.
        """
        where: InheritorPredicate,
        "Limit the amount of classes returned"
        limit: Int
    ): [InheritanceTreeClass!]!
}

"Represents a reference in the form of the class referencing the method/field and how many times it is referenced in that class"
type Reference {
    "The class in which this reference is contained"
    owner: ClassDefinition!
    "How many times the referenced method/field was referenced in the class"
    referenceCount: Int! @orderBy
}

"""
Represents a type that can be referenced by other classes.
Can be method or a field.
"""
interface Referenceable {
    "Returns the references to this element"
    references(
        "Optional filter to apply to the query"
        where: ReferencePredicate,
        "Limit the amount of references returned"
        limit: Int
    ): [Reference!]!
}

"Represents a method as returned by `Class.methods`"
type Method @implement(interfaces: ["Identifiable", "Referenceable"]) {
    "The name of this method"
    name: String!
    "The descriptor of this method"
    descriptor: String!
}

"Represents a method as returned by `Class.fields`"
type Field @implement(interfaces: ["Identifiable", "Referenceable"]) {
    "The name of this field"
    name: String!
    """
    The type of this field
    Can be a JVM internal class like like `java/lang/Object` or a type descriptor like `I`, `Z` or `[Ljava/lang/Object;`.
    """
    type: String!
}

"A concrete definition of a class"
type ClassDefinition @implement(interfaces: "Annotatable") {
    "The name of this class"
    name: String! @orderBy

    "Classes this class directly inherits from (both super classes and interfaces)"
    parents: [String!]

    "The mod that defines this definition"
    mod: LightweightMod!

    """
    The methods this class defines directly.
    Note that this list is not complete and only contains methods relevant for API usage. Therefore private methods that have no annotations are not tracked.
    """
    methods(
        "Optional filter to apply to the query"
        where: MethodPredicate,
        "Limit the amount of methods returned"
        limit: Int
    ): [MethodDefinition!]!

    """
    The fields this class defines directly.
    Note that this list is not complete and only contains fields relevant for API usage. Therefore private fields that have no annotations are not tracked.
    """
    fields(
        "Optional filter to apply to the query"
        where: FieldPredicate,
        "Limit the amount of fields returned"
        limit: Int
    ): [FieldDefinition!]!

    """
    The methods this class references.
    Note that this list is not complete and only contains references relevant for API usage. Therefore references to private, static or non-overriding methods of classes in the same mod are not tracked.
    """
    referencedMethods: [ReferencedMethod!]!

    """
    The fields this class references.
    Note that this list is not complete and only contains references relevant for API usage. Therefore references to private or static fields of classes in the same mod are not tracked.
    """
    referencedFields: [ReferencedField!]!
}

"Represents a reference to a method within a concrete class definition"
type ReferencedMethod {
    "The name of the class of the referenced method"
    class: String!
    "The name of the referenced method"
    name: String!
    "The descriptor of the referenced method"
    descriptor: String!
    "How many times this method was referenced in the class definition"
    referenceCount: Int!
}

"Represents a reference to a field within a concrete class definition"
type ReferencedField {
    "The name of the class of the referenced field"
    class: String!
    "The name of the referenced field"
    name: String!
    "The type of the referenced field"
    type: String!
    "How many times this field was referenced in the class definition"
    referenceCount: Int!
}

"A concrete definition of a method"
type MethodDefinition @implement(interfaces: "Annotatable") {
    "The name of this method"
    name: String! @orderBy
    "The descriptor of this method"
    descriptor: String! @orderBy
}

"A concrete definition of a field"
type FieldDefinition @implement(interfaces: "Annotatable") {
    "The name of this method"
    name: String! @orderBy
    "The type of this field. This is not a descriptor so classes are in internal JVM format (e.g. `java/lang/String` instead of `Ljava/lang/String;`)"
    type: String! @orderBy
}

"Used to filter methods based on different criteria"
input MethodPredicate @predicateType @oneOf {
    "Filter based on the method's name"
    name: StringPredicate
    "Filter based on the method's descriptor"
    descriptor: StringPredicate
}

"Used to filter fields based on different criteria"
input FieldPredicate @predicateType @oneOf {
    "Filter based on the field's name"
    name: StringPredicate
    "Filter based on the field's type"
    type: StringPredicate
}

"Used to filter references based on different criteria"
input ReferencePredicate @predicateType @oneOf {
    "Filter based on the mod that the reference is part of"
    mod: ModPredicate
    "Filter based on the amount of references"
    referenceCount: IntPredicate
}

"Used to filter tags based on different criteria"
input TagFilePredicate @predicateType @oneOf {
    "Filter based on the tag name"
    name: StringPredicate

    """
    If set to true, only tags that override existing values will be returned.
    If set to false, only tags that do not override existing values will be returned.
    """
    replace: Boolean

    "A tag file will match this predicate if any of its direct entries matches the given predicate"
    anyEntry: StringPredicate
}

"Used to filter data map files based on different criteria"
input DataMapFilePredicate @predicateType @oneOf {
    "Filter based on the data map name"
    name: StringPredicate
}

"Used to filter enum extension entries based on different criteria"
input EnumExtensionPredicate @predicateType @oneOf {
    "Filter based on the internal name of the enum the extension is for"
    enum: StringPredicate
    "Filter based on the enum constructor the extension uses"
    constructor: String
    "Filter based on the name of the enum value the extension adds"
    name: String
}

"Used to filter mods based on different criteria"
input ModPredicate @predicateType @oneOf {
    "Filter based on the mod's name (derived from mod metadata, jar contents or maven coordinates)"
    name: StringPredicate
    "Filter based on the mod's authors (derived from mod metadata)"
    authors: StringPredicate
    "Filter based on the mod's license (derived from mod metadata)"
    license: StringPredicate
    "Filter based on the mod's description (derived from mod metadata)"
    description: StringPredicate
    """
    Filter based on the mod's mod IDs (derived from mod metadata).
    On Neo/Forge only one of the IDs of a multi mod jar needs to match the filter.
    """
    modId: StringPredicate

    "A mod will match if any of the classes it defines matches the given predicate"
    anyClass: ClassDefinitionPredicate
    "A mod will match if any of the manifest attributes its jar has matches the given filter"
    anyManifestAttribute: ManifestAttributePredicate

    "A mod will match if it is contained in the pack with the given ID"
    inPack: ProjectId

    "A mod will match if it is associated with the CurseForge project with the given ID"
    curseforgeProjectId: Int
    "A mod will match if it is associated with the Modrinth project with the given ID"
    modrinthProjectId: String

    "A mod will match if the date it has last been indexed on matches the given predicate"
    indexed: DatePredicate
}

"Represents the ID of a project on CurseForge or Modrinth"
input ProjectId @oneOf {
    "The ID of the project on CurseForge"
    curseforge: Int
    "The ID of the project on Modrinth"
    modrinth: String
}

"Used to filter classes based on different criteria"
input ClassPredicate @predicateType @oneOf {
    "Filter based on the class' JVM name"
    name: StringPredicate
}

"Used to filter class definitions based on different criteria"
input ClassDefinitionPredicate @predicateType @oneOf {
    "Filter based on the class' JVM name"
    name: StringPredicate

    "A class definition will match if any of the methods it defines matches the given predicate"
    anyMethod: MethodPredicate
    "A class definition will match if any of the fields it defines matches the given predicate"
    anyField: FieldPredicate
}

"Used to filter manifest attributes based on their name and/or value"
input ManifestAttributePredicate @predicateType @oneOf {
    "Filter based on the attribute name (key)"
    name: StringPredicate
    "Filter based on the attribute value"
    value: StringPredicate
}

"Information about pagination in a connection."
type PageInfo {
    "Whether there are more elements past the last element of the response"
    hasNextPage: Boolean!

    """
    Whether there are more elements before the last element of the response.
    Note that this field may be false even if earlier pages exist when it is too expensive to check if earlier pages exist.
    """
    hasPreviousPage: Boolean!

    "The cursor ID that points to the first element returned, if there is one"
    startCursor: ID

    "The cursor ID that points to the last element returned, if there is one"
    endCursor: ID
}

"""
Represents a way of filtering string inputs based on different rules that are either logical operators
on other filters (NOT, AND, OR) or exact / regex matches.
"""
input StringPredicate @oneOf @predicateType {
    "The string being filtered must be equal to the given string."
    equals: String

    "The string being filtered must match the given regex pattern."
    matches: String

    "The string being filtered must start with the given string."
    startsWith: String
}

"""
Represents a way of filtering numbers based on different rules that are either logical operators
on other filters (NOT, AND, OR) or number comparisons.
"""
input IntPredicate @oneOf @predicateType {
    "The number being filtered must be less than the given number."
    lessThan: Int
    "The number being filtered must be greater than the given number."
    greaterThan: Int

    "The number being filtered must be less than or equal to the given number."
    lessThanOrEqual: Int
    "The number being filtered must be greater than or equal to the given number."
    greaterThanOrEqual: Int

    "The number being filtered must be equal to the given number."
    equals: Int

    "The number being filtered must be even if this is set to true, or odd otherwise."
    isEven: Boolean
}

"A predicate applied to date types"
input DatePredicate @oneOf {
    "Matches if the date is before (smaller than) the given date"
    before: DateTime
    "Matches if the date is after (greater than) the given date"
    after: DateTime
}

enum OrderRule {
    value,
    length
}

enum OrderDirection {
    asc,
    desc
}

input OrderMethod {
    by: OrderRule = value
    direction: OrderDirection = asc
}
