plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.1.20'
    id 'com.apollographql.apollo' version '4.1.1'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.apollographql.apollo:apollo-runtime:4.1.1")
}

apollo {
    service("service") {
        packageName.set("net.neoforged.waifu.apiplay")
        introspection {
            endpointUrl.set("http://localhost:6532/graphql")
            schemaFile.set(file("src/main/graphql/net/neoforged/waifu/apiplay/schema.json"))
        }
        generateOptionalOperationVariables = false
        generateInputBuilders = true
    }
}
