name: Deploy Images to GHCR

on:
  push:
    branches:
      - v2
    paths:
      - src/**
      - gradle/**
      - build.gradle
      - Dockerfile
      - gradle.properties
      - gradlew.bat
      - .github/**
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: neoforged/actions/checkout@main

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew :build :shadowJar

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/neoforged/whatamiforgingup:v2 --tag ghcr.io/neoforged/whatamiforgingup:latest
          docker push ghcr.io/neoforged/whatamiforgingup:v2
          docker push ghcr.io/neoforged/whatamiforgingup:latest
