name: Publish Grafana Plugin

on:
  push:
    branches:
      - v2
    paths:
      - neoforged-waifuvis-app/**
      - .github/**
  workflow_dispatch:

env:
  NODE_VERSION: 22

permissions:
  contents: write
  statuses: write

jobs:
  push-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: neoforged/actions/checkout@main

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: neoforged-waifuvis-app/package-lock.json

      - name: Update Plugin Version
        run: ./gradlew replacePluginVersion

      - name: Install NPM Dependencies
        working-directory: neoforged-waifuvis-app
        run: npm ci

      - name: Build Plugin
        working-directory: neoforged-waifuvis-app
        run: npm run build

      - name: Publish with Gradle
        run: ./gradlew publishMods
        env:
            GITHUB_TOKEN: ${{ github.token }}
